### ISSUE TITLE
Fix relative path being relative to install location and not requesting file

### ISSUE THREAD

**Issue by jlmorgan** [anthonynichols/node-include#2]
Given the following project layout:

```
projectA/
  node_modules/
    include/
    projectB/
      src/
        index.js
  src/
    index.js
```

If `projectB` also uses `include` to include file relative to the project root, when evaluating `include`, `projectB` will use `projectA`'s root instead since `npm` installs the common module at the top-most level instead of each child directory. As a result, all calls to `include` pull from the root of the top-most instead of the one for the calling file.

Since no method exists to determine the path of the requesting file from within the module, the path must be provided up front. While some other solutions attempt to do this, they rely on static passing of `../../../../` et cetera into the function returned by the `require` (i.e., `require-root`).

This could be resolved by allowing `include` to function like the following:

```javascript
var include = require("include")(__dirname);

var data = include("fixtures/data");
var method = include("src/method");
```

**Comment by anthonynichols** [comment]
Hey @jlmorgan thanks for bringing this up - It has been a while since I looked at this project and it's about time to bring it up to speed with everything else going on with the Node / NPM world as of late.

I could totally be wrong, but I think NPM 3 in Node 5 has flattened out the module directory structure, so something like this is necessary to get everything rewired correctly. I'm going to take a look into things later this afternoon and possibly write some tests against it to make sure things are working as desired.

Expect further communication and / or merging your pull request in later. Thanks again for your contribution!

**Comment by jlmorgan** [comment]
Sure thing. We use this extensively in our projects at work for all project references.

**Comment by anthonynichols** [comment]
Sorry for the delay in getting around to this - between a birthday and Blizzcon, I have been super busy and distracted. I'll be updating things this week!
